
---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/arnest.in/msp

    - &University
        Name: UniversityMSP

        ID: UniversityMSP

        MSPDir: crypto-config/peerOrganizations/university.arnest.in/msp

        AnchorPeers:
            - Host: peer0.university.arnest.in
              Port: 7051

Application: &ApplicationDefaults

    Organizations:

Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.arnest.in:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

Profiles:

    UniversityOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            UniversityConsortium:
                Organizations:
                    - *University
    UniversityChannel:
        Consortium: UniversityConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *University

